### ISSUE TITLE
Please include aria2-fast patch

### ISSUE THREAD

**Issue by chromer030** [abcfy2/aria2-static-build#3]
Thank you for this useful repo.
Please include [aria2-fast](https://aur.archlinux.org/packages/aria2-fast) patch , provided in Arch Linux AUR.

**Comment by abcfy2** [comment]
I have no plans to add other third party patches at this time. Because this repository has a continuous build: https://github.com/abcfy2/aria2-static-build/releases/tag/continuous

Any patches that have not been officially merged may break down the CI/CD.

Thanks.
