### ISSUE TITLE
i686 windows build

### ISSUE THREAD

**Issue by MagicalDrizzle** [abcfy2/aria2-static-build#4]
would it be possible to change the 64bit windows build script to accommodate 32bit builds?

**Comment by abcfy2** [comment]
Did you still have 32bit Windows ?

Because mingw64 only support Windows 7 or later, which almost no 32bit users.

**Comment by MagicalDrizzle** [comment]
I'm actually trying to build this for ReactOS (~server 2003), which is 32bit "only" for now

**Comment by abcfy2** [comment]
https://github.com/aria2/aria2/releases/tag/release-1.36.0 official release contains 32bit build. Did it work for you ?

**Comment by MagicalDrizzle** [comment]
it does, but i'm kinda finding some CI project to build with the latest library and yours seem to be perfect ^^
and yeah that build works!

**Comment by abcfy2** [comment]
Add `i686-w64-mingw32` build in continuous build: https://github.com/abcfy2/aria2-static-build/releases/download/continuous/aria2-i686-w64-mingw32_static.zip
