### ISSUE TITLE
Can I package it into a Python wheel?

### ISSUE THREAD

**Issue by WSH032** [abcfy2/aria2-static-build#6]
作者你好，非常感谢你开发了这个仓库。

我最近在寻找合适的aria2构建来打包成python wheel，方便python用户安装。

你的库看起来非常不错，而且最近也有更新。

只是我有几个疑问，如果能得到你的解答将非常感激。

- 我可以把这个库的二进制文件打包成python wheel吗？（指许可证方面）
- static build就意味着不需要动态库吗？也就是说只要架构正确，在大多数linux发行版上都可以直接运行，而不需要额外的库对吗？
- 我想从release页面下载相应的二进制文件。想询问一下，是否以后有可能对已发布的release进行修改呢？
  - 如果有可能困扰到你的话，我也可以fork后自己创建release。

非常感谢您。

**Comment by abcfy2** [comment]
- aria2本身基于GPL v2 协议分发，所以下游进行二进制分发理论上是没什么问题的（GPLv2协议要求一并包含构建源码，以便其他用户可以复刻），你当然也可以继续分发二进制程序
- 我的static build包含了所有的依赖（这一点你可以从`build.sh`的脚本中具体看出来），所以理论上不需要系统有其他任何依赖，而且当初采用musl做底层的C环境也是考虑到musl比glibc更容易静态链接，而且对内核版本没有要求，而glibc静态链接通常对Linux内核版本有要求，在`file`输出可以看到。我曾经在手机上测试过arm和arm64(adb 上传之后在adb shell中运行)，都是没问题的，也在我家的arm路由器上测试过，不过mips设备我手头并没有，只是在qemu环境运行过而已
- 已发布的稳定release如无必要通常不会大动

目前release页面会有stable release (以aria2 版本号命名，基于aria2 tag构建)和一个 Pre-release (以continuous命名，采取每周持续集成构建的方案，基于aria2 master分支以及所有最新依赖构建)。如果你期望尝鲜，那么可以始终从类似于 https://github.com/abcfy2/aria2-static-build/releases/download/continuous/aria2-aarch64-linux-musl_libressl_static.zip 这样的URL下载最新的构建，如果你期望使用aria2最新稳定版本，那么可以始终从类似于 https://github.com/abcfy2/aria2-static-build/releases/latest/download/aria2-aarch64-linux-musl_libressl_static.zip 这样的URL下载最新稳定构建

**Comment by abcfy2** [comment]
目前构建脚本基本已经稳定，所以维护量也不算太大了，也不费太大功夫了，欢迎PR。

目前也就是偶尔遇到weekly build失败的，修复一下就行了，也不浪费太多精力，还维护的过来，偶尔看看aria2有没有最新版本，有的话加一个tag就会自动发布稳定构建了，基本都自动化了

**Comment by WSH032** [comment]
非常感谢你的快速回复！

目前我打算固定住1.37的版本，我会采用类似[pyright-python](https://github.com/RobertCraigie/pyright-python)的方式开发。

测试的话不用担心，我可以用[cibuildwheel](https://github.com/pypa/cibuildwheel)来进行测试。

---

![image](https://github.com/abcfy2/aria2-static-build/assets/126865849/c18d67e2-16b3-422b-918a-f8ace4a504cb)

![image](https://github.com/abcfy2/aria2-static-build/assets/126865849/05a635bb-60cf-4821-b94a-8360865936ee)

我对架构不是很了解。我想我可能需要打包以上这6个架构。

- i686-w64-mingw32就对应 win 32咯？
- win arm64没有好像
- linux i686好像也没有对吗？

其他的架构我在你的仓库找到了。

**Comment by abcfy2** [comment]
理论上musllinux应该可以不加，这个不是musl动态链接，所以可以不需要依赖musl运行时，也不需要glibc运行时，理论上manylinux就够了

i686-w64-mingw32是win32架构，使用mingw构建的，linux i686没有加，构建的时候可能用的人不多，所以没构建，加上去也很容易。

win arm64好像暂时没有工具链，回头我得找到能用的可以考虑加上

**Comment by WSH032** [comment]
好的，到时候wheel的tag我写通用的linux就行。

我先把常用的架构打包了，主要是windows 32/64。linux那边一般都可以用类似`apt`的命令行一键安装，就不太需要wheel。

**Comment by WSH032** [comment]
我已经快要完成了: https://github.com/WSH032/aria2-wheel

测试已经通过了，正处于等待发布的状态。

如果你愿意的话，可以在这里一起添加你为作者：
https://github.com/WSH032/aria2-wheel/blob/8381f7d0680fa8dadc849f60b8eb09297ffe9fd5/pyproject.toml#L7-L9

期待你的意见 😀

**Comment by abcfy2** [comment]
谢谢，我并未在你的项目提交代码贡献，所以作者可以不用加我，只需要保留我的项目链接即可。

如有需要我这边构建上的帮助，欢迎提交PR和issue

**Comment by WSH032** [comment]
好的，我把Credits部分提到前面来说了，然后我还添加了构建这个wheels的脚本指引。

---

我已经发布了这个项目 <https://pypi.org/project/aria2/>

如果有人想尝试的话，`pip install aria2`即可。

---

### 关于今后发展

构建这个wheel最重要环节是从你的仓库下载zip归档，然后我假设zip内的根目录一定存在`aria2c.exe`这样的可执行文件。

相关代码：
- https://github.com/WSH032/aria2-wheel/blob/af15756d45344057706c622195e91b8c888626a2/hatch_build.py#L29-L30
- https://github.com/WSH032/aria2-wheel/blob/af15756d45344057706c622195e91b8c888626a2/hatch_build.py#L158-L168

今后的更新，只要你这边不改变zip归档的命名风格（就比如`aria2-{BUILD}_static.zip`）和zip内文件结构（根目录存在aria2c.exe），我这边的构建就不会破坏。

并没有强求的意思，只是如果发生相应更改时，你能@我一下，就非常感谢了🥰

---

### 希望的新feature

希望能在这个仓库获得 macos 的静态构建，这样就能覆盖全平台了。

相关 issue #2

---

最后，再次感谢你的指导和你的对这个仓库的工作！✨

**Comment by abcfy2** [comment]
一直没加MacOS是因为我手头没有MacOS测试环境，也没有找到交叉工具链，所以一直没加而已

**Comment by WSH032** [comment]
确实有点麻烦。我之前看的这个仓库 <https://github.com/q3aql/aria2-static-builds> ，他的作者也是没有macos机器来测试，所以也没弄macos。

aria2官方仓库里的issue到是有[个人fork的构建](https://github.com/aria2/aria2/issues/1820#issuecomment-958635992)，但是其他人维护的仓库不如你的仓库稳定，目前没找到和你一样以发布1.37版本的仓库。

---

不过macos应该不像linux系统那样那么混乱吧？在github actions上构建出来二进制文件，即使不是完全的静态，应该也能在其他人的macos上跑？

如果能有一个macos_amd64的构建就非常棒了🎃

**Comment by abcfy2** [comment]
找了个能在虚拟机run起来的黑苹果，也许不久之后就有macos build
